#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#    Copyright 2010-2013, Chaz Littlejohn
#    
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#    
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU General Public License for more details.
#    
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

########################################################################

from datetime import datetime
import pytz

class MergeStructures:
    
    def __init__(self):
        self.versions = [pytz.utc.localize(datetime.strptime(d, "%Y/%m/%d %H:%M:%S")) for d in ("2013/05/28 00:00:00",)]
        self.versions.append(datetime.utcnow().replace(tzinfo = pytz.utc))
        self.SnG_Structures = []
        self.SnG_Structures.append({  
                            '$1 NL Holdem Double Up - 10 Handed'    : {'buyIn': 1,   'fee': 0.08, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (2,2,2,2,2)},
                            '$1 PL Omaha Double Up - 10 Handed'     : {'buyIn': 1,   'fee': 0.08, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (2,2,2,2,2)},
                            '$10 Bounty SnG - 6 Handed'             : {'buyIn': 5,   'fee': 1,    'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (21, 9)},
                            '$10 Bounty SnG - 9 Handed'             : {'buyIn': 5,   'fee': 1,    'currency': 'USD', 'seats': 9, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (22.5, 13.5, 9)},
                            '$10 Bounty SnG - 10 Handed'            : {'buyIn': 5,   'fee': 1,    'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (25, 15, 10)},
                            '$10 NL Holdem Double Up - 10 Handed'   : {'buyIn': 10,  'fee': 0.8,  'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (20,20,20,20,20)},
                            '$10 PL Omaha Double Up - 10 Handed'    : {'buyIn': 10,  'fee': 0.8,  'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (20,20,20,20,20)},
                            '$10 Winner Takes All - $60 Coupon'     : {'buyIn': 10,  'fee': 0.8,  'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (60,)},
                            '$100 Bounty SnG - 6 Handed'            : {'buyIn': 100, 'fee': 9,    'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (315, 135)},
                            '$100 NL Holdem Double Up - 10 Handed'  : {'buyIn': 100, 'fee': 8,    'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (200,200,200,200,200)},
                            '$100 PL Omaha Double Up - 10 Handed'   : {'buyIn': 100, 'fee': 8,    'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (200,200,200,200,200)},
                            '$100,000 Guaranteed - Super Turbo Satellite' : {'buyIn': 38.8, 'fee': 0.8, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (109,109,11,3.8)},
                            '$10 Bounty SnG - 6 Handed'             : {'buyIn': 5, 'fee': 1,    'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (25, 15, 10)},
                            '$10 Satellite'                         : {'buyIn': 10,  'fee': 1,    'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (60,)},
                            '$100 Bounty SnG - 6 Handed'            : {'buyIn': 100, 'fee': 9,    'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (315, 135)},
                            '$11 Coupon - Super Turbo Satellite'    : {'buyIn': 1.84,  'fee': 0.05,    'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (11,0.04)},
                            '$2 Bounty SnG - 10 Handed'             : {'buyIn': 2,   'fee': 0.2,  'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10,6,4)},
                            '$2 Bounty SnG - 6 Handed'              : {'buyIn': 2,   'fee': 0.2,  'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (7, 3, 2)},
                            '$2 NL Holdem All-In or Fold 10 - Handed' : {'buyIn': 2,   'fee': 0.16, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10,6,4)},
                            '$2 NL Holdem Double Up - 10 Handed'    : {'buyIn': 2,   'fee': 0.16, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (4,4,4,4,4)},
                            '$2 PL Omaha Double Up - 10 Handed'     : {'buyIn': 2,   'fee': 0.16, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (4,4,4,4,4)},
                            '$2 Satellite'                          : {'buyIn': 2,   'fee': 0.2,  'currency': 'USD', 'seats': 5,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (11,)},
                            '$20 Bounty SnG - 10 Handed'            : {'buyIn': 20,  'fee': 2,    'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (50, 30, 30)},
                            '$20 Bounty SnG - 9 Handed'             : {'buyIn': 20,  'fee': 2,    'currency': 'USD', 'seats': 9, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (45, 27, 18)},
                            '$20 Bounty SnG - 6 Handed'             : {'buyIn': 20,  'fee': 2,    'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (42, 18)},
                            '$20 Daily Deep Stack Satellite'        : {'buyIn': 20,  'fee': 2,    'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (109, 11)},
                            '$20 NL Holdem Double Up - 10 Handed'   : {'buyIn': 20,  'fee': 1.6,  'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (40,40,40,40,40)},
                            '$20 NL Holdem Double Up - 10 Handed Turbo' : {'buyIn': 20,  'fee': 1.4,  'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (40,40,40,40,40)},
                            '$3 NL Holdem Double Up - 10 Handed'    : {'buyIn': 3,   'fee': 0.24, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (6,6,6,6,6)},
                            '$3 PL Omaha Double Up - 10 Handed'    : {'buyIn': 3,   'fee': 0.24, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (6,6,6,6,6)},
                            '$3.30 - 90 Man - Unlimited Rebuys and Addon SNG' : {'buyIn': 3,   'fee': 0.3, 'currency': 'USD', 'seats': 9, 'max': 90, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (81, 58.05, 40.5, 29.7, 20.25, 14.85, 10.8)},
                            '$30 Bounty SnG - 6 Handed'             : {'buyIn': 30,  'fee': 3,    'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (84, 36)},
                            '$33 Coupon - Super Turbo Satellite'    : {'buyIn': 11,  'fee': 0.2,    'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (33, 33)},
                            '$33 Turbo - 6 Max'                     : {'buyIn': 30,  'fee': 3,    'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (126, 54)},
                            '$5 Bounty SnG - 10 Handed'             : {'buyIn': 5,   'fee': 0.5,  'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (12.50, 7.50, 5)},
                            '$5 Bounty SnG - 9 Handed'              : {'buyIn': 5,   'fee': 0.5,  'currency': 'USD', 'seats': 9, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (11.25, 6.75, 4.5)},
                            '$5 Bounty SnG - 6 Handed'              : {'buyIn': 5,   'fee': 0.5,  'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (14, 6)},
                            '$5 NL Holdem All-In or Fold - 10 Handed': {'buyIn': 5,   'fee': 0.4,  'currency': 'USD', 'seats': 10,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (25, 15, 10)},
                            '$5 NL Holdem Double Up - 6 Handed'     : {'buyIn': 5,   'fee': 0.4,  'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (10,10,10)},
                            '$5 NL Holdem Double Up - 10 Handed'    : {'buyIn': 5,   'fee': 0.4,  'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10,10,10,10,10)},
                            '$5 NL Holdem Double Up - 10 Handed Turbo' : {'buyIn': 5,   'fee': 0.35,  'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10,10,10,10,10)},
                            '$5 PL Omaha Double Up - 10 Handed'     : {'buyIn': 5,   'fee': 0.4,  'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10,10,10,10,10)},
                            '$50 NL Holdem Double Up - 10 Handed'   : {'buyIn': 50,  'fee': 4,    'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10,10,10,10,10)},
                            '$50 PL Omaha Double Up - 10 Handed'    : {'buyIn': 50,  'fee': 4,    'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10,10,10,10,10)},
                            '$55 Turbo - 6 Max'                     : {'buyIn': 50,  'fee': 4,    'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (210, 90)},
                            '$60 Coupon - Super Turbo Satellite'    : {'buyIn': 10,  'fee': 0.19, 'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (60,)},
                            '$60 Daily High Roller SnG Satellite'   : {'buyIn': 55,  'fee': 5,    'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (215, 115)},
                            '$75 Bounty SnG - 6 Handed'             : {'buyIn': 75,  'fee': 7.5,  'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (210, 90)},
                            '$82 Turbo - 6 Max'                     : {'buyIn': 75,  'fee': 7,    'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (315, 135)},
                            '**NEW** Bumblebee Room - 3 Minute Levels'    : {'buyIn': 0.1, 'fee': 0.01, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (0.39, 0.21)},
                            '**NEW** Coyote Room - 3 Minute Levels'       : {'buyIn': 50, 'fee': 2, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (195, 105)},
                            '**NEW** Dragonfly Room - 3 Minute Levels'    : {'buyIn': 2, 'fee': 0.12, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (7.80, 4.20)},
                            '**NEW** Fruit Fly Room - 3 Minute Levels'    : {'buyIn': 1, 'fee': 0.06, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (3.90, 2.1)},
                            '**NEW** Gazelle Room - 3 Minute Levels'      : {'buyIn': 100, 'fee': 3.7, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (390, 210)},
                            '**NEW** Greyhound Room - 3 Minute Levels'    : {'buyIn': 35, 'fee': 1.5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (136.5, 73.5)},
                            '**NEW** Hare Room - 3 Minute Levels'         : {'buyIn': 20, 'fee': 0.9, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (78, 42)},
                            '**NEW** Hummingbird Room - 3 Minute Levels'  : {'buyIn': 5, 'fee': 0.3, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (19.50, 10.50)},
                            '**NEW** Killer Whale Room - 3 Minute Levels' : {'buyIn': 500, 'fee': 12, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (1950, 1050)},
                            '**NEW** Marlin Room - 3 Minute Levels'       : {'buyIn': 350, 'fee': 10, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (1365, 735)},
                            '**NEW** Sailfish Room - 3 Minute Levels'     : {'buyIn': 209, 'fee': 7, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (815.10, 438.90)},
                            '**NEW** Swift Room - 3 Minute Levels'        : {'buyIn': 10, 'fee': 0.5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (39, 21)},
                            '100 Man Shootout Satellite - 4 x $109 tickets guaranteed!':  {'buyIn': 5,  'fee': 0.5,    'currency': 'USD', 'seats': 10, 'max': 100,  'multi': True, 'payoutCurrency': 'USD', 'payouts': (109, 109, 109, 109, 64)},
                            '100 VIP Point SnG'                     : {'buyIn': 1,   'fee': 0.05, 'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (0,0)},
                            '250 VIP Point SnG'                     : {'buyIn': 2.5, 'fee': 0.15, 'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (0,0)},
                            '500 VIP Point SnG'                     : {'buyIn': 5,   'fee': 0.25, 'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (0,0)},
                            'Aardvark Room'                         : {'buyIn': 10,  'fee': 1,    'currency': 'USD', 'seats': 9,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (45,27,18)},
                            'Alligator Room - Heads Up'             : {'buyIn': 100, 'fee': 4.5,  'currency': 'USD', 'seats': 2,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (200,)},
                            'Alligator Room - Turbo Heads Up'       : {'buyIn': 110, 'fee': 4.5,  'currency': 'USD', 'seats': 2,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (220,)},
                            'Alpaca Room - Turbo'                   : {'buyIn': 10,  'fee': 1,    'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (42, 18)},
                            'Anaconda Room - Heads Up'              : {'buyIn': 100, 'fee': 4.5,  'currency': 'USD', 'seats': 2,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (200,)},
                            'Anaconda Room - Turbo Heads Up'        : {'buyIn': 110, 'fee': 4.5,  'currency': 'USD', 'seats': 2,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (220,)},
                            'Anchovy Room - Super Turbo HU'         : {'buyIn': 4, 'fee': 0.15,  'currency': 'USD', 'seats': 2,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (8,)},
                            'Anteater Room'                         : {'buyIn': 10,  'fee': 1,    'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (42, 18)},
                            'Antelope Room'                         : {'buyIn': 5,   'fee': 0.5,  'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (21, 9)},
                            'Arctic Fox Room - Heads Up'            : {'buyIn': 2,   'fee': 0.1, 'currency': 'USD', 'seats': 2,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (4,)},
                            'Armadillo Room'                        : {'buyIn': 20,  'fee': 2,    'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (100, 60, 40)},
                            'Aussie Millions - Super Turbo Satelite': {'buyIn': 10,  'fee': 1,    'currency': 'USD', 'seats': 6,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (60,)},
                            'Axolotyl Room - Heads Up'              : {'buyIn': 30,  'fee': 1.5,  'currency': 'USD', 'seats': 2,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (60,)},
                            'Axolotyl Room - Turbo Heads Up'        : {'buyIn': 33,  'fee': 1.5,  'currency': 'USD', 'seats': 2,  'multi': False, 'payoutCurrency': 'USD', 'payouts': (66,)},
                            'Badger Room'                           : {'buyIn': 10,  'fee': 1, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (50, 30, 20)},
                            'Bandicoot Room'                        : {'buyIn': 2,   'fee': 0.2, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (8.40, 3.60)},
                            'Barramundi Room - Super Turbo'         : {'buyIn': 20,   'fee': 0.9, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (84, 36)},
                            'Bear Room'                             : {'buyIn': 50,  'fee': 5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (210, 90)},
                            'Bear Room - Heads Up'                  : {'buyIn': 200, 'fee': 9, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (400,)},
                            'Bear Room - Turbo Heads Up'            : {'buyIn': 220, 'fee': 9, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (440,)},
                            'Beaver Room'                           : {'buyIn': 5, 'fee': 0.5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (21, 9)},
                            'Beaver Room 12 min levels'             : {'buyIn': 5,   'fee': 0.5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (21, 9)},
                            'Beaver Room 12 min levels Short Handed' : {'buyIn': 5, 'fee': 0.5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (21, 9)},
                            'Bilby Room - Heads Up'                 : {'buyIn': 5, 'fee': 0.25, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10,)},
                            'Bilby Room - Turbo Heads Up'           : {'buyIn': 7, 'fee': 0.25, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (14,)},
                            'Bison Room - Heads Up'                 : {'buyIn': 50, 'fee': 2.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (100,)},
                            'Bison Room - Turbo Heads Up'           : {'buyIn': 55, 'fee': 2.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (110,)},
                            'Black Bear Room Turbo Heads Up (4 player)' : {'buyIn': 4, 'fee': 0.6, 'currency': 'USD', 'seats': 2, 'max': 4, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (48,)},
                            'Black Mamba Room - Super Turbo'        : {'buyIn': 12, 'fee': 52, 'currency': 'USD', 'seats': 6, 'max': 12, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (312, 187.2, 124.8)},
                            'Blackfish Room - Super Turbo'          : {'buyIn': 5, 'fee': 0.3, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (21,9)},
                            'Blue Ringed Octopus Room - Super Turbo HU' : {'buyIn': 8, 'fee': 0.2, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (16,)},
                            'Blue Swimmer Crab - Super Turbo HU'    : {'buyIn': 15, 'fee': 0.3, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (30,)},
                            'Boar Room - Heads Up'                  : {'buyIn': 20, 'fee': 1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (40,)},
                            'Boar Room - Turbo Heads Up'            : {'buyIn': 22, 'fee': 1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (44,)},
                            'Bobcat Room'                           : {'buyIn': 20, 'fee': 2, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (84, 36)},
                            'Botfly Room - Super Turbo HU'          : {'buyIn': 8, 'fee': 0.2, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (16,)},
                            'Bottlenose Dolphin Room - Super Turbo' : {'buyIn': 100, 'fee': 3.70, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (420, 180)},
                            'Buffalo Room'                          : {'buyIn': 10, 'fee': 1, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (42, 18)},
                            'Buffalo Room - Heads Up'               : {'buyIn': 300, 'fee': 12, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (600,)},
                            'Buffalo Room - Turbo Heads Up'         : {'buyIn': 330, 'fee': 12, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (660,)},
                            'Bumblebee Room - Super Turbo'          : {'buyIn': 0.1, 'fee': 0.01, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (0.42, 0.18)},
                            'Bunyip Room - Heads Up'                : {'buyIn': 100, 'fee': 4.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (200,)},
                            'Bunyip Room - Turbo Heads Up'          : {'buyIn': 110, 'fee': 4.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (220,)},
                            'Bushmaster Room Super Turbo HU'        : {'buyIn': 250, 'fee': 4, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (500,)},
                            'Caiman Room'                           : {'buyIn': 20, 'fee': 2, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (84, 36)},
                            'Camel Room'                            : {'buyIn': 10, 'fee': 1, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (42, 18)},
                            'Cape Hunting Dog Room'                 : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 9, 'max': 45, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (27.90, 19.35, 14.85, 11.25, 8.10, 5.40, 3.15)},
                            'Capra room - Heads Up'                 : {'buyIn': 5, 'fee': 0.25, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10,)},
                            'Capybara Room'                         : {'buyIn': 5, 'fee': 0.5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (21, 9)},
                            'Cassowary Room'                        : {'buyIn': 5, 'fee': 0.5, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (25, 15, 10)},
                            'Cobra Room - Heads Up'                 : {'buyIn': 10, 'fee': 0.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (20,)},
                            'Cobra Room - Turbo Heads Up'           : {'buyIn': 11, 'fee': 0.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (22,)},
                            'Coconut Crab Room - Super Turbo'       : {'buyIn': 35, 'fee': 1.5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (147, 63)},
                            'Condor Room - Heads Up'                : {'buyIn': 30, 'fee': 1.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (60,)},
                            'Condor Room - Turbo Heads Up'          : {'buyIn': 33, 'fee': 1.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (66,)},
                            'Conga Eel Room - Super Turbo HU'       : {'buyIn': 120, 'fee': 2.3, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (240,)},
                            'Cougar Room - Heads Up'                : {'buyIn': 20, 'fee': 1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (40,)},
                            'Cougar Room - Turbo Heads Up'          : {'buyIn': 22, 'fee': 1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (44,)},
                            'Coyote Room - Super Turbo'             : {'buyIn': 50, 'fee': 2, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (210, 90)},
                            'Cricket Room - Super Turbo 6 Max'      : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 6, 'max': 18, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (14.40, 10.8, 7.2, 3.6)},
                            'Crocodile Room'                        : {'buyIn': 5, 'fee': 0.5, 'currency': 'USD', 'seats': 9, 'max': 18, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (36, 27, 18, 9)},
                            'Daily High Roller - Super Turbo Satellite' : {'buyIn': 72, 'fee': 1.3, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (215, 215, 2)},
                            'Dingo Room - Heads Up'                 : {'buyIn': 50, 'fee': 2.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (100,)},
                            'Dingo Room - Turbo Heads Up'           : {'buyIn': 55, 'fee': 2.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (110,)},
                            'Dollar Dazzler Turbo'                  : {'buyIn': 1, 'fee': 0.1, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (5, 3, 2)},
                            'Dolphin Room'                          : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10, 6, 4)},
                            'Dragon Room'                           : {'buyIn': 100, 'fee': 9, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (420, 180)},
                            'Dragonfly Room - Super Turbo'          : {'buyIn': 2, 'fee': 0.12, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (8.40, 3.60)},
                            'Dugong Room'                           : {'buyIn': 50, 'fee': 5, 'currency': 'USD', 'seats': 9, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (225, 135, 90)},
                            'Eagle Room'                            : {'buyIn': 10, 'fee': 1, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (42, 18)},
                            'Eagle Room 12 min levels'              : {'buyIn': 10, 'fee': 1, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (50, 30, 20)},
                            'Eagle Room 12 min levels Short Handed' : {'buyIn': 10, 'fee': 1, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (42, 18)},
                            'Echidna Room'                          : {'buyIn': 5, 'fee': 0.5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (21, 9)},
                            'Elephant Room - Heads Up'              : {'buyIn': 100, 'fee': 4.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (200,)},
                            'Elephant Room - Turbo Heads Up'        : {'buyIn': 110, 'fee': 4.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (220,)},
                            'Elephant Shrew Room'                   : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 9, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (9, 5.40, 3.60)},
                            'Elk Room'                              : {'buyIn': 50, 'fee': 5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (210, 90)},
                            'Emperor Penguin Room'                  : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 90, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (0,) },
                            'Emperor Penguin Room Turbo'            : {'buyIn': 2.20, 'fee': 0.2, 'currency': 'USD', 'seats': 90, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (0,) },
                            'Emu Room - Heads Up'                   : {'buyIn': 10, 'fee': 0.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (20,)},
                            'Emu Room - Turbo Heads Up'             : {'buyIn': 11, 'fee': 0.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (22,)},
                            'Falcon Room'                           : {'buyIn': 50, 'fee': 5, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (250, 150, 100)},
                            'Falcon Room Turbo'                     : {'buyIn': 50, 'fee': 5, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (250, 150, 100)},
                            'Fast Fifty SnG'                        : {'buyIn': 0.5, 'fee': 0.1, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (2.50, 1.50, 1)},
                            'Fast Fifty Turbo'                      : {'buyIn': 0.5, 'fee': 0.1, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (2.50, 1.50, 1)},
                            'Ferret Room - Turbo'                   : {'buyIn': 10, 'fee': 1, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (50, 30, 20)},
                            'Fox Room - Heads Up'                   : {'buyIn': 10, 'fee': 1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (20,)},
                            'Fox Room - Turbo Heads Up'             : {'buyIn': 11, 'fee': 0.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (22,)},
                            'Frigate Bird Room Super Turbo HU'      : {'buyIn': 2, 'fee': 0.1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (4,)},
                            'Fruit Fly Room - Super Turbo'          : {'buyIn': 1, 'fee': 0.06, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (4.20, 1.80)},
                            'Fusilier Room Turbo'                   : {'buyIn': 1, 'fee': 0.1, 'currency': 'USD', 'seats': 9, 'max': 45, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (13.96, 9.68, 7.42, 5.62, 4.05, 2.70, 1.57)},
                            'Fun Step 1'                            : {'buyIn': 0, 'fee': 0, 'currency': 'FREE', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (0, 0, 0)},
                            'Fun Step 2'                            : {'buyIn': 0, 'fee': 0, 'currency': 'FREE', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (0, 0, 0)},
                            'Fun Step 3'                            : {'buyIn': 0, 'fee': 0, 'currency': 'FREE', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (1, 0, 0)},
                            'Galapagos Turtle - Super Turbo HU'     : {'buyIn': 120, 'fee': 2.30, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (240,)},
                            'Gazelle Room - Super Turbo'            : {'buyIn': 100, 'fee': 3.7, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (420, 180)},
                            'Gecko Room'                            : {'buyIn': 30, 'fee': 3, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (150, 90, 60)},
                            'Gecko Room Turbo'                      : {'buyIn': 30, 'fee': 3, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (150, 90, 60)},
                            'Gibbon Room'                           : {'buyIn': 200, 'fee': 15, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (840, 360)},
                            'Giraffe Room'                          : {'buyIn': 20, 'fee': 2, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (84, 36)},
                            'Goldfish Room'                         : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (8.40, 3.60)},
                            'Gopher Room - Turbo'                   : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (8.40, 3.60)},
                            'Gorilla Room - Heads Up'               : {'buyIn': 20, 'fee': 1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (40,)},
                            'Gorilla Room - Turbo Heads Up'         : {'buyIn': 20, 'fee': 1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (40,)},
                            'Gnat Room - Super Turbo HU'            : {'buyIn': 4, 'fee': 0.15, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (8,)},
                            'Goblin Shark Room'                     : {'buyIn': 150, 'fee': 2.75, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (300,)},
                            'Goblin Shark Room - Super Turbo HU'    : {'buyIn': 150, 'fee': 2.75, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (300,)},
                            'Golden Eagle Turbo HU'                 : {'buyIn': 22, 'fee': 1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (44,)},
                            'Goldfish Room'                         : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (8.40, 3.60)},
                            'Great White Shark Room - Heads Up'     : {'buyIn': 2000, 'fee': 40, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (4000,)},
                            'Great White Shark Room - Turbo Heads Up' : {'buyIn': 2200, 'fee': 40, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (4400,)},
                            'Grey Wolf Room Turbo HU (4 player)'    : {'buyIn': 18, 'fee': 0.9, 'currency': 'USD', 'seats': 2, 'max': 4, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (72,)},
                            'Greyhound Room - 2 Minute Levels'      : {'buyIn': 35, 'fee': 1.5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (136.5, 73.5)},
                            'Greyhound Room - Super Turbo'          : {'buyIn': 35, 'fee': 1.5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (147, 63)},
                            'Grizzly Room'                          : {'buyIn': 30, 'fee': 3, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (126, 54)},
                            'Guinea Pig Room - Super Turbo'         : {'buyIn': 5, 'fee': 0.3, 'currency': 'USD', 'seats': 6, 'max': 12, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (30, 18, 12)},
                            'Hairy Frog Room - Super Turbo HU'      : {'buyIn': 28, 'fee': 0.7, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (56,)},
                            'Hare Room - Super Turbo'               : {'buyIn': 20, 'fee': 0.9, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (84, 36)},
                            'Hedgehog Room'                         : {'buyIn': 5, 'fee': 0.5, 'currency': 'USD', 'seats': 9, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (22.50, 13.50, 9)},
                            'Heron Room'                            : {'buyIn': 300, 'fee': 20, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (1260, 540)},
                            'Hippo Room - Heads Up'                 : {'buyIn': 50, 'fee': 2.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (100,)},
                            'Hippo Room - Turbo Heads Up'           : {'buyIn': 55, 'fee': 2.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (110,)},
                            'Honey Badger Room'                     : {'buyIn': 5, 'fee': 5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (21, 9)},
                            'Howler Monkey Room - Super Turbo'      : {'buyIn': 10, 'fee': 0.5, 'currency': 'USD', 'seats': 6, 'max': 12, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (60, 36, 24)},
                            'Hummingbird Room - Super Turbo'        : {'buyIn': 5, 'fee': 0.3, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (21, 9)},
                            'Hyena Room'                            : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10, 6, 4)},
                            'Ibex Room - Super Turbo HU'            : {'buyIn': 180, 'fee': 3.1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (360,)},
                            'Iguana Room - Heads Up'                : {'buyIn': 20, 'fee': 1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (40,)},
                            'Iguana Room - Turbo Heads Up'          : {'buyIn': 22, 'fee': 1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (44,)},
                            'Impala Room'                           : {'buyIn': 30, 'fee': 3, 'currency': 'USD', 'seats': 9, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (135, 81, 54)},
                            'Jaguar Room'                           : {'buyIn': 50, 'fee': 5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (210, 90)},
                            'Killer Whale Room - Super Turbo'       : {'buyIn': 500, 'fee': 12, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (2100, 900)},
                            'King Cobra Room - Super Turbo HU'      : {'buyIn': 500, 'fee': 7.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (1000,)},
                            'King Crab Room - Super Turbo HU'       : {'buyIn': 28, 'fee': 0.7, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (56,)},
                            'King Tuna Room - Super Turbo'          : {'buyIn': 50, 'fee': 2, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (210, 90)},
                            'Komodo Room'                           : {'buyIn': 50, 'fee': 5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (210, 90)},
                            'Kookaburra Room - Heads Up'            : {'buyIn': 20, 'fee': 1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (40,)},
                            'Kookaburra Room - Turbo Heads Up'      : {'buyIn': 22, 'fee': 1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (44,)},
                            'Lemming Room - Super Turbo HU'         : {'buyIn': 40, 'fee': 0.8, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (80,)},
                            'Lemur Room - Super Turbo HU'           : {'buyIn': 55, 'fee': 1.1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (110,)},
                            'Leopard Room'                          : {'buyIn': 5, 'fee': 0.5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (21, 9)},
                            'Leopard Seal Room - Heads Up'          : {'buyIn': 30, 'fee': 1.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (60,)},
                            'Lion Room - Heads Up'                  : {'buyIn': 1000, 'fee': 30, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (2000,)},
                            'Lion Room - Turbo Heads Up'            : {'buyIn': 1100, 'fee': 30, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (2200,)},
                            'Lizard Room - Turbo'                   : {'buyIn': 20, 'fee': 2, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (84, 36)},
                            'Lynx Room'                             : {'buyIn': 110, 'fee': 9, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (462, 198)},
                            'Mako Room'                             : {'buyIn': 75, 'fee': 7, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (375, 225, 150)},
                            'Mako Room Turbo'                       : {'buyIn': 75, 'fee': 7, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (375, 225, 150)},
                            'Mallard Room'                          : {'buyIn': 100, 'fee': 9, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (420, 180)},
                            'Mandrill Room'                         : {'buyIn': 5, 'fee': 0.5, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (25, 15, 10)},
                            'Marlin Room - Super Turbo'             : {'buyIn': 350, 'fee': 10, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (1470, 630)},
                            'Meerkat Room - Turbo'                  : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (8.40, 3.60)},
                            'Mink Room - Heads Up'                  : {'buyIn': 5, 'fee': 0.25, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10,)},
                            'Mink Room - Turbo Heads Up'            : {'buyIn': 7, 'fee': 0.25, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (14,)},
                            'Mountain Goat Room Turbo HU (4 player)' : {'buyIn': 6, 'fee': 0.3, 'currency': 'USD', 'seats': 2, 'max': 4, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (24,)},
                            'Mongoose Room'                         : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10, 6, 4)},
                            'Monkey Room'                           : {'buyIn': 10, 'fee': 1, 'currency': 'USD', 'seats': 9, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (90, 54, 36)},
                            'Mountain Lion Turbo HU'                : {'buyIn': 75, 'fee': 3.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (150,)},
                            'Mouse Room'                            : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10, 6, 4)},
                            'Musk Rat Room'                         : {'buyIn': 3, 'fee': 0.3, 'currency': 'USD', 'seats': 8, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (16.80, 7.20)},
                            'Ocelot Room'                           : {'buyIn': 10, 'fee': 1, 'currency': 'USD', 'seats': 8, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (56, 24)},
                            'Orangutan Room'                        : {'buyIn': 20, 'fee': 2, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (84, 36)},
                            'Otter Room - Turbo'                    : {'buyIn': 5, 'fee': 0.5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (21, 9)},
                            'Ox Room - Turbo'                       : {'buyIn': 20, 'fee': 2, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (100, 60, 40)},
                            'Panda Room - Heads Up'                 : {'buyIn': 100, 'fee': 4.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (200,)},
                            'Panda Room - Turbo Heads Up'           : {'buyIn': 110, 'fee': 4.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (220,)},
                            'Panther Room - Heads Up'               : {'buyIn': 500, 'fee': 20, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (1000,)},
                            'Panther Room - Turbo Heads Up'         : {'buyIn': 550, 'fee': 20, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (1100,)},
                            'Peregrine Room'                        : {'buyIn': 330, 'fee': 20, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (1386, 594)},
                            'Pilchard Room Turbo'                   : {'buyIn': 1, 'fee': 0.1, 'currency': 'USD', 'seats': 9, 'max': 18, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (7.20, 5.40, 3.60, 1.80)},
                            'Piranha Room - Heads Up'               : {'buyIn': 50, 'fee': 2.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (100,)},
                            'Piranha Room - Turbo Heads Up'         : {'buyIn': 55, 'fee': 2.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (110,)},
                            'Polar Bear Room - Super Turbo HU'      : {'buyIn': 500, 'fee': 7.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (1000,)},
                            'Pond Skater Room - Super Turbo HU'     : {'buyIn': 15, 'fee': 0.3, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (30,)},
                            'Platypus Room'                         : {'buyIn': 5, 'fee': 0.5, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (25, 15, 10)},
                            'Pronghorn Antelope Room - Super Turbo HU' : {'buyIn': 1000, 'fee': 15, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (2000,)},
                            'Puffin Room - Super Turbo HU'          : {'buyIn': 70, 'fee': 1.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (140,)},
                            'Puma Room - Heads Up'                  : {'buyIn': 20, 'fee': 1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (40,)},
                            'Puma Room - Turbo Heads Up'            : {'buyIn': 22, 'fee': 1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (44,)},
                            'Rabbit Room - Turbo'                   : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10, 6, 4)},
                            'Racoon Room'                           : {'buyIn': 5, 'fee': 0.5, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (25, 15, 10)},
                            'Rattlesnake Room - Heads Up'           : {'buyIn': 5, 'fee': 0.25, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10,)},
                            'Rattlesnake Room - Turbo Heads Up'     : {'buyIn': 5.75, 'fee': 0.25, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (11.50,)},
                            'Raven Room'                            : {'buyIn': 180, 'fee': 14, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (756, 324)},
                            'Razorback Room'                        : {'buyIn': 100, 'fee': 9, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (420, 180)},
                            'Red Kangaroo Room - Heads Up'          : {'buyIn': 20, 'fee': 1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (40,)},
                            'Rhino Room - Heads Up'                 : {'buyIn': 10, 'fee': 0.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (20,)},
                            'Rhino Room - Turbo Heads Up'           : {'buyIn': 11, 'fee': 0.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (22,)},
                            'Sailfish Room - Super Turbo'           : {'buyIn': 209, 'fee': 7, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (877.80, 376.20)},
                            'Salmon Room'                           : {'buyIn': 5, 'fee': 0.5, 'currency': 'USD', 'seats': 9, 'max': 45, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (69.76, 48.38, 37.12, 28.12, 20.25, 13.50, 7.87)},
                            'Sardine Room Turbo'                    : {'buyIn': 1, 'fee': 0.1, 'currency': 'USD', 'seats': 9, 'max': 27, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (10.27, 7.02, 4.59, 2.75, 2.37)},
                            'Sea Eagle Room Turbo HU (4 player)'    : {'buyIn': 24, 'fee': 1.2, 'currency': 'USD', 'seats': 2, 'max': 4, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (96,)},
                            'Silverfish Room - Super Turbo'         : {'buyIn': 10, 'fee': 5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (42, 18)},
                            'Sea Kraits Room - Super Turbo HU'      : {'buyIn': 70, 'fee': 1.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (140,)},
                            'Secretary Bird Room - Super Turbo HU'  : {'buyIn': 90, 'fee': 1.8, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (180,)},
                            'Shrew Room - Heads Up'                 : {'buyIn': 5, 'fee': 0.25, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10,)},
                            'Shrew Room - Turbo Heads Up'           : {'buyIn': 7, 'fee': 0.25, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (14,)},
                            "Snakes'n'Ladders Step 1"               : {'buyIn': 1, 'fee': 0.1, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (3.30, 3.30, 1.10, 1.10, 1.10, 0.10)},
                            "Snakes'n'Ladders Step 2"               : {'buyIn': 3, 'fee': 0.3, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (11, 11, 3.30, 3.30, 1.10, 0.30)},
                            "Snakes'n'Ladders Step 3"               : {'buyIn': 10, 'fee': 1, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (32.50, 32.50, 11, 11, 3.30, 3.30, 3.30, 1.10, 1.10, 0.90)},
                            "Snakes'n'Ladders Step 4"               : {'buyIn': 30, 'fee': 2.5, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (80, 80, 80, 32.50, 11, 11, 3.30, 1.10, 1.10)},
                            "Snakes'n'Ladders Step 5"               : {'buyIn': 75, 'fee': 5, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (265, 265, 80, 80, 32.50, 11, 11, 3.30, 1.10, 1.10)},
                            "Snakes'n'Ladders Step 6"               : {'buyIn': 255, 'fee': 10, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (530, 530, 530, 265, 265, 265, 80, 80, 3.30, 1.70)},
                            "Snakes'n'Ladders Step 7"               : {'buyIn': 510, 'fee': 20, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (2000, 1250, 750, 499.50, 295, 220, 80, 3.30, 1.10, 1.10)},
                            'Snow Goose Room'                       : {'buyIn': 10, 'fee': 1, 'currency': 'USD', 'seats': 9, 'max': 45, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (139.50, 96.75, 74.25, 56.25, 40.50, 27, 15.75)},
                            'Southern Stingray Room - Super Turbo HU' : {'buyIn': 55, 'fee': 1.1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (110,)},
                            'Springbok Room - Super Turbo'          : {'buyIn': 20, 'fee': 0.9, 'currency': 'USD', 'seats': 6, 'max': 12, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (120, 72, 48)},
                            'Squirrel Room - Turbo'                 : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (8.40, 3.60)},
                            'Stag Room Turbo HU (4 player)'        : {'buyIn': 3, 'fee': 0.15, 'currency': 'USD', 'seats': 2, 'max': 4, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (12,)},
                            'Starling Room'                         : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 9, 'max': 180, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (108, 72, 36, 28.80, 21.60, 18, 14.40, 10.80, 8.10, 6.30, 3.60, 3.60, 3.60, 3.60, 3.60, 3.60, 3.60, 3.60, 3.60, 3.60) },
                            'Starling Room TURBO'                   : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 9, 'max': 180, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (108, 72, 36, 28.80, 21.60, 18, 14.40, 10.80, 8.10, 6.30, 3.60, 3.60, 3.60, 3.60, 3.60, 3.60, 3.60, 3.60, 3.60, 3.60) },
                            'STEP 1 AIOF Sng'                       : {'buyIn': 1, 'fee': 0.1, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (5.50, 1.10, 1.10, 1.10, 0.20)},
                            'STEP 10 AIOF Final Sng'                : {'buyIn': 1170, 'fee': 10, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (2250, 90)},
                            'STEP 2 AIOF Sng'                       : {'buyIn': 5.25, 'fee': 0.25, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10.50,)},
                            'STEP 3 AIOF Sng'                       : {'buyIn': 10, 'fee': 0.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (20,)},
                            'STEP 4 AIOF Sng'                       : {'buyIn': 19.5, 'fee': 0.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (39,)},
                            'STEP 5 AIOF Sng'                       : {'buyIn': 38.5, 'fee': 0.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (77,)},
                            'STEP 6 AIOF Sng'                       : {'buyIn': 76, 'fee': 1, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (152,)},
                            'STEP 7 AIOF Sng'                       : {'buyIn': 150, 'fee': 2, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (300,)},
                            'STEP 8 AIOF Sng'                       : {'buyIn': 297, 'fee': 3, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (594,)},
                            'STEP 9 AIOF Sng'                       : {'buyIn': 590, 'fee': 4, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (1180,)},
                            'Sun Bear Room'                         : {'buyIn': 20, 'fee': 2, 'currency': 'USD', 'seats': 8, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (112, 48)},
                            'Swift Room - Super Turbo'              : {'buyIn': 10, 'fee': 0.5, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (42, 18)},
                            'Swordfish Room'                        : {'buyIn': 220, 'fee': 15, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (924, 396)},
                            'T-Rex Room - Heads Up'                 : {'buyIn': 5000, 'fee': 80, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10000,)},
                            'T-Rex Room - Turbo Heads Up'           : {'buyIn': 5500, 'fee': 80, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (11000,)},
                            'Tapir Room'                            : {'buyIn': 20, 'fee': 2, 'currency': 'USD', 'seats': 8, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (112, 48)},
                            'Termite Room'                          : {'buyIn': 3, 'fee': 0.3, 'currency': 'USD', 'seats': 8, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (16.80, 7.20)},
                            'Tetra Room Turbo'                      : {'buyIn': 1, 'fee': 0.1, 'currency': 'USD', 'seats': 90, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (0,) },
                            'Tiger Fish Room'                       : {'buyIn': 10, 'fee': 1, 'currency': 'USD', 'seats': 8, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (56, 24,)},
                            'Tiger Room - Heads Up'                 : {'buyIn': 50, 'fee': 2.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (100,)},
                            'Tiger Room - Turbo Heads Up'           : {'buyIn': 55, 'fee': 2.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (100,)},
                            'Tiger Shark - Super Turbo'             : {'buyIn': 209, 'fee': 7, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (877.80, 376.20)},
                            'Timber Wolf Room'                      : {'buyIn': 400, 'fee': 22, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (1680, 720)},
                            'Toucan Room - Heads Up'                : {'buyIn': 10, 'fee': 0.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (20,)},
                            'Toucan Room - Heads Up'                : {'buyIn': 10, 'fee': 0.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (20,)},
                            'Toucan Room - Turbo Heads Up'          : {'buyIn': 11, 'fee': 0.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (22,)},
                            'Tsetse Fly Room'                       : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (8.4,3.6)},
                            'Turkey Room - Heads Up'                : {'buyIn': 10, 'fee': 0.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (20,)},
                            'Turkey Room - Turbo Heads Up'          : {'buyIn': 11, 'fee': 0.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (22,)},
                            'Viper Room - Heads Up'                 : {'buyIn': 1000, 'fee': 40, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (2000,)},
                            'Vulture Room'                          : {'buyIn': 20, 'fee': 2, 'currency': 'USD', 'seats': 9, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (90,54,36)},
                            'Wallaby Room'                          : {'buyIn': 10, 'fee': 1, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (42, 18)},
                            'Walrus Room'                           : {'buyIn': 50, 'fee': 5, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (250, 150, 100)},
                            'Warthog Room'                          : {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 9, 'max': 18, 'multi': True, 'payoutCurrency': 'USD', 'payouts': (18, 10.80, 7.20)},
                            'Waterbuck room - Heads Up'             : {'buyIn': 10, 'fee': 0.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (20,)},
                            'Whale Room - Heads Up'                 : {'buyIn': 500, 'fee': 20, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (1000,)},
                            'Whale Shark Room - Super Turbo'        : {'buyIn': 500, 'fee': 12, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (2100,900)},
                            'White Whale Room Super Turbo HU'       : {'buyIn': 250, 'fee': 4, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (500,)},
                            'Wildebeest Room'                       : {'buyIn': 10, 'fee': 1, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (42, 18)},
                            'Wolf Spider Room - Super Turbo HU'     : {'buyIn': 21, 'fee': 0.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (42,)},
                            'Wolverine Room'                        : {'buyIn': 50, 'fee': 0.5, 'currency': 'USD', 'seats': 10, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (25, 15, 10)},
                            'Wombat Room'                           : {'buyIn': 20, 'fee': 1, 'currency': 'USD', 'seats': 6, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (84, 36)},
                            'Yak Room - Heads Up'                   : {'buyIn': 50, 'fee': 2.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (100,)},
                            'Zebra Room - Heads Up'                 : {'buyIn': 5, 'fee': 0.25, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (10,)},
                            'Zebra Room - Turbo Heads Up'           : {'buyIn': 7, 'fee': 0.25, 'currency': 'USD', 'seats': 2, 'multi': False, 'payoutCurrency': 'USD', 'payouts': (14,)},
                         })
        self.SnG_Structures.append({
                            'Regular - $1.10': {'buyIn': 0.95, 'fee': 0.15, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (4.28, 2.56, 1.71)},
                            'Regular - $109': {'buyIn': 100, 'fee': 9, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (450, 270, 180)},
                            'Regular - $11': {'buyIn': 10, 'fee': 1, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (45, 27, 18)},
                            'Regular - $2.20': {'buyIn': 1.95, 'fee': 0.25, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (8.78, 5.26, 3.51)},
                            'Regular - $22': {'buyIn': 20, 'fee': 2, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (90, 54, 36)},
                            'Regular - $215': {'buyIn': 200, 'fee': 15, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (900, 450, 360)},
                            'Regular - $33': {'buyIn': 30, 'fee': 3, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (135, 81, 54)},
                            'Regular - $5.50': {'buyIn': 4.95, 'fee': 0.55, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (22.28, 13.36, 8.91)},
                            'Regular - $60': {'buyIn': 55, 'fee': 5, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (247.50, 148.50, 99)},
                            'Regular HU - $1.10': {'buyIn': 1.01, 'fee': 0.09, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (2.02,)},
                            'Regular HU - $109': {'buyIn': 103.25, 'fee': 5.75, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (206.5,)},
                            'Regular HU - $11': {'buyIn': 10.22, 'fee': 0.78, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (20.44,)},
                            'Regular HU - $2.20': {'buyIn': 2.03, 'fee': 0.17, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (4.06,)},
                            'Regular HU - $215': {'buyIn': 204.55, 'fee': 10.45, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (409.1,)},
                            'Regular HU - $22': {'buyIn': 20.5, 'fee': 1.5, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (41,)},
                            'Regular HU - $33': {'buyIn': 30.9, 'fee': 2.1, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (61.8,)},
                            'Regular HU - $5.50': {'buyIn': 5.1, 'fee': 0.4, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (10.2,)},
                            'Regular HU - $60': {'buyIn': 56.4, 'fee': 3.6, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'USD', 'payouts': (112.8,)},
                            'Step & Go - Step 1': {'buyIn': 0.97, 'fee': 0.13, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (5.50, 1.10, 1.10, 1.03)},
                            'Step & Go - Step 2': {'buyIn': 5.04, 'fee': 0.46, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (11, 11, 5.50, 5.50, 5.50, 5.50, 1.10, 0.26)},
                            'Step & Go - Step 3': {'buyIn': 10.17, 'fee': 0.83, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (33, 33, 11, 5.50, 5.50, 1.10, 1.10, 1.10, 0.23)},
                            'Step & Go - Step 4': {'buyIn': 30.51, 'fee': 2.49, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (60, 60, 60, 33, 33, 11, 11, 5.50, 1.09)},
                            'Step & Go - Step 5': {'buyIn': 55.5, 'fee': 4.5, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (109, 109, 109, 60, 60, 33, 11, 5.50, 3)},
                            'Step & Go - Step 6': {'buyIn': 101, 'fee': 8, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (250, 160, 130, 110, 85, 70, 60, 33, 11)},
                            'Turbo - $1.10': {'buyIn': 0.97, 'fee': 0.13, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (4.37, 2.62, 1.74)},
                            'Turbo - $1.10 (6-max)': {'buyIn': 0.97, 'fee': 0.13, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (3.79, 203)},
                            'Turbo - $109': {'buyIn': 101, 'fee': 8, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (454.50, 272.70, 181.80)},
                            'Turbo - $109 (6-max)': {'buyIn': 101, 'fee': 8, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (393.90, 212.10)},
                            'Turbo - $11 (6-max)': {'buyIn': 10.17, 'fee': 0.83, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (39.67, 21.35)},
                            'Turbo - $11': {'buyIn': 10.17, 'fee': 0.83, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (45.77, 27.46, 18.30)},
                            'Turbo - $2.20': {'buyIn': 1.96, 'fee': 0.24, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (8.83, 5.29, 3.52)},
                            'Turbo - $2.20 (6-max)': {'buyIn': 1.96, 'fee': 0.24, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (7.65, 4.11)},
                            'Turbo - $215': {'buyIn': 202, 'fee': 13, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (909, 545.40, 363.60)},
                            'Turbo - $215 (6-max)': {'buyIn': 202, 'fee': 13, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (787.80, 424.20)},
                            'Turbo - $22': {'buyIn': 20.34, 'fee': 1.66, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (91.54, 54.91, 36.61)},
                            'Turbo - $22 (6-max)': {'buyIn': 20.34, 'fee': 1.66, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (78.33, 42.71)},
                            'Turbo - $33': {'buyIn': 30.51, 'fee': 2.49, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (137.30, 82.38, 54.91)},
                            'Turbo - $33 (6-max)': {'buyIn': 30.51, 'fee': 2.49, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (118.99, 64.07)},
                            'Turbo - $5.50': {'buyIn': 5.04, 'fee': 0.46, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (22.69, 13.60, 9.07)},
                            'Turbo - $5.50 (6-max)': {'buyIn': 5.04, 'fee': 0.46, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (19.66, 10.58)},
                            'Turbo - $60': {'buyIn': 55.5, 'fee': 4.5, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (249.75, 149.85, 99.9)},
                            'Turbo - $60 (6-max)': {'buyIn': 55.5, 'fee': 4.5, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (216.45, 116.55)},
                            'Turbo HU - $1.1': {'buyIn': 1.03, 'fee': 0.07, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (2.06,)},
                            'Turbo HU - $11': {'buyIn': 10.48, 'fee': 0.52, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (20.96,)},
                            'Turbo HU - $2.20': {'buyIn': 2.07, 'fee': 0.13, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (4.14,)},
                            'Turbo HU - $33': {'buyIn': 31.44, 'fee': 1.56, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (62.88,)},
                            'Hyper Turbo HU - $1,050': {'buyIn': 1030, 'fee': 20, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (2060,)},
                            'Hyper Turbo HU - $1.10': {'buyIn': 1.06, 'fee': 0.04, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (2.12,)},
                            'Hyper Turbo HU - $11': {'buyIn': 10.48, 'fee': 0.52, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (21.58,)},
                            'Hyper Turbo HU - $109': {'buyIn': 106.91, 'fee': 2.09, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (213.82,)},
                            'Hyper Turbo HU - $2.20': {'buyIn': 2.14, 'fee': 0.06, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (4.28,)},
                            'Hyper Turbo HU - $215': {'buyIn': 210.89, 'fee': 4.11, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (421.78,)},
                            'Hyper Turbo HU - $22': {'buyIn': 21.58, 'fee': 0.42, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (43.16,)},
                            'Hyper Turbo HU - $33': {'buyIn': 32.37, 'fee': 0.63, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (64.74,)},
                            'Hyper Turbo HU - $5.50': {'buyIn': 5.39, 'fee': 0.11, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (10.78,)},
                            'Hyper Turbo HU - $530': {'buyIn': 519.85, 'fee': 10.15, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (1039.70,)},
                            'Hyper Turbo HU - $60': {'buyIn': 58.85, 'fee': 1.15, 'currency': 'USD', 'seats': 2, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (117.70,)},
                            'Hyper Turbo - $0.11': {'buyIn': 0.1, 'fee': 0.01, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (0.39, 0.21)},
                            'Hyper Turbo - $1.10': {'buyIn': 1.01, 'fee': 0.09, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (3.94, 2.12)},
                            'Hyper Turbo - $109': {'buyIn': 105.15, 'fee': 3.85, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (410.09, 220.81)},
                            'Hyper Turbo - $11': {'buyIn': 10.48, 'fee': 0.52, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (40.88, 22)},
                            'Hyper Turbo - $2.20': {'buyIn': 2.05, 'fee': 0.15, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (8, 4.30)},
                            'Hyper Turbo - $215': {'buyIn': 208.03, 'fee': 6.97, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (811.32, 436.86)},
                            'Hyper Turbo - $22': {'buyIn': 21.05, 'fee': 0.95, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (82.10, 44.20)},
                            'Hyper Turbo - $33': {'buyIn': 31.65, 'fee': 1.35, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (123.44, 66.46)},
                            'Hyper Turbo - $5.50': {'buyIn': 5.19, 'fee': 0.31, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (20.25, 10.89)},
                            'Hyper Turbo - $60': {'buyIn': 57.68, 'fee': 2.32, 'currency': 'USD', 'seats': 6, 'multi': False, 'speed': 'Hyper', 'payoutCurrency': 'USD', 'payouts': (224.96, 121.12)},
                            'Cobra Room': {'buyIn': 1000, 'fee': 0, 'currency': 'play', 'seats': 10, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'play', 'payouts': (5000, 3000, 2000)},
                            'Eagle Room': {'buyIn': 2000, 'fee': 0, 'currency': 'play', 'seats': 10, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'play', 'payouts': (10000, 6,000, 4,000)},
                            'Grizzly Room': {'buyIn': 10000, 'fee': 0, 'currency': 'play', 'seats': 10, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'play', 'payouts': (50000, 30000, 20000)},
                            'Lion Room': {'buyIn': 5000, 'fee': 0, 'currency': 'play', 'seats': 10, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'play', 'payouts': (25000, 15000, 10000)},
                            'Shark Room': {'buyIn': 50000, 'fee': 0, 'currency': 'play', 'seats': 10, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'play', 'payouts': (250000, 150000, 100000)},
                            'Wombat Room': {'buyIn': 250, 'fee': 0, 'currency': 'play', 'seats': 10, 'multi': False, 'speed': 'Normal', 'payoutCurrency': 'play', 'payouts': (1000, 600, 400)},
                            'Double or Nothing - $1.10': {'buyIn': 0.99, 'fee': 0.11, 'currency': 'USD', 'seats': 10, 'multi': False, 'speed': 'Turbo', 'doubleOrNothing': True, 'payoutCurrency': 'USD', 'payouts': (1.98, 1.98, 1.98, 1.98, 1.98)},
                            'Double or Nothing - $109': {'buyIn': 103.25, 'fee': 5.75, 'currency': 'USD', 'seats': 10, 'multi': False, 'speed': 'Turbo', 'doubleOrNothing': True, 'payoutCurrency': 'USD', 'payouts': (206.50, 206.50, 206.50, 206.50, 206.50)},
                            'Double or Nothing - $11': {'buyIn': 10.35, 'fee': 0.65, 'currency': 'USD', 'seats': 10, 'multi': False, 'speed': 'Turbo', 'doubleOrNothing': True, 'payoutCurrency': 'USD', 'payouts': (20.70, 20.70, 20.70, 20.70, 20.70)},
                            'Double or Nothing - $2.20': {'buyIn': 2, 'fee': 0.2, 'currency': 'USD', 'seats': 10, 'multi': False, 'speed': 'Turbo', 'doubleOrNothing': True, 'payoutCurrency': 'USD', 'payouts': (4, 4, 4, 4, 4)},
                            'Double or Nothing - $22': {'buyIn': 20.72, 'fee': 1.28, 'currency': 'USD', 'seats': 10, 'multi': False, 'speed': 'Turbo', 'doubleOrNothing': True, 'payoutCurrency': 'USD', 'payouts': (41.44, 41.44, 41.44, 41.44, 41.44)},
                            'Double or Nothing - $33': {'buyIn': 31.1, 'fee': 1.9, 'currency': 'USD', 'seats': 10, 'multi': False, 'speed': 'Turbo', 'doubleOrNothing': True, 'payoutCurrency': 'USD', 'payouts': (62.20, 62.20, 62.20, 62.20, 62.20)},
                            'Double or Nothing - $5.50': {'buyIn': 5.1, 'fee': 0.4, 'currency': 'USD', 'seats': 10, 'multi': False, 'speed': 'Turbo', 'doubleOrNothing': True, 'payoutCurrency': 'USD', 'payouts': (10.20, 10.20, 10.20, 10.20, 10.20)},
                            'Double or Nothing - $60': {'buyIn': 56.6, 'fee': 3.4, 'currency': 'USD', 'seats': 10, 'multi': False, 'speed': 'Turbo', 'doubleOrNothing': True, 'payoutCurrency': 'USD', 'payouts': (113.20, 113.20, 113.20, 113.20, 113.20)},
                            'Knockout - $1.10': {'buyIn': 0.99, 'fee': 0.11, 'bounty': 0.2, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (3.56, 2.13, 1.42)},
                            'Knockout - $109': {'buyIn': 102, 'fee': 7, 'bounty': 20.4, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (367.20, 220.32, 146.88)},
                            'Knockout - $11': {'buyIn': 10.12, 'fee': 0.88, 'bounty': 2.02, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (36.45, 21.87, 14.58)},
                            'Knockout - $2.20': {'buyIn': 1.98, 'fee': 0.22, 'bounty': 0.4, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (7.12, 4.26, 2.84)},
                            'Knockout - $22': {'buyIn': 20.39, 'fee': 1.61, 'bounty': 4.08, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (73.40, 44.04, 29.35)},
                            'Knockout - $33': {'buyIn': 30.58, 'fee': 2.42, 'bounty': 6.12, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (110.08, 66.04, 44.02)},
                            'Knockout - $5.50': {'buyIn': 5.03, 'fee': 0.47, 'bounty': 1, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (18.14, 10.88, 7.25)},
                            'Knockout - $60': {'buyIn': 55.75, 'fee': 4.25, 'bounty': 11.15, 'currency': 'USD', 'seats': 9, 'multi': False, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (200.70, 120.42, 80.28)},
                            'Turbo 18 Man - $1.10': {'buyIn': 0.97, 'fee': 0.13, 'currency': 'USD', 'seats': 9, 'max': 18, 'multi': True, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (6.99, 5.24, 3.49, 1.74)},
                            'Turbo 18 Man - $11': {'buyIn': 10.17, 'fee': 0.83, 'currency': 'USD', 'seats': 9, 'max': 18, 'multi': True, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (73.23, 54.92, 36.61, 18.30)},
                            'Turbo 18 Man - $5.5': {'buyIn': 5.04, 'fee': 0.46, 'currency': 'USD', 'seats': 9, 'max': 18, 'multi': True, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (36.29, 27.22, 18.14, 9.07)},
                            'Turbo 45 Man - $1.10': {'buyIn': 0.97, 'fee': 0.13, 'currency': 'USD', 'seats': 9, 'max': 45, 'multi': True, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (13.62, 9.35, 7.16, 5.46, 3.88, 2.61, 1.57)},
                            'Turbo 45 Man - $11': {'buyIn': 10.17, 'fee': 0.83, 'currency': 'USD', 'seats': 9, 'max': 45, 'multi': True, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (142.79, 97.94, 75.06, 57.21, 40.73, 27.45, 16.47)},
                            'Turbo 45 Man - $5.5': {'buyIn': 5.04, 'fee': 0.46, 'currency': 'USD', 'seats': 9, 'max': 45, 'multi': True, 'speed': 'Turbo', 'payoutCurrency': 'USD', 'payouts': (70.77, 48.54, 37.20, 28.35, 20.18, 13.6, 8.16)},
                            })
        
    def lookupSnG(self, key, startTime):
        for i in range(len(self.versions)):
            if startTime < self.versions[i]:
                struct = self.SnG_Structures[i].get(key)
                return struct
        
    